### PR TITLE
Make sure that sub-resources are correctly initialized in default con…

### LINKED ISSUE #28: Subresource on same line generates invalid default constructor.
**Describe the bug**
When a resource with a sub-resource is defined on the same line the default constructor of the parent resource class does not properly initialize the sub-resource.

**To Reproduce**
1. Create a RAML that contains the following resource definition.
```
/projects/rename:
      put:
        description: Rename a project
        body:
          #schema: projectName
        responses:
          202:
          404:
```
2. Generate client code
3. Try to compile the generated source 
4. There is a error *The blank final field rename may not have been initialized* on the default constructor for the projects resource class  (`resource/projects/Projects.java`).

**Expected behavior**
The subresource attribute should be initialized to `null` in the default constructor as is the case when defining the subresource on a second line.

### PR DESCRIPTION
**Pull request by ullgren**
…structor. Fixes #28.

### CODE REVIEW

**Comment by ullgren** [comment]
Let me know if you merge PR #27 first and I will update this PR to work with the V2 output version.

**Comment by machaval** [comment]
I did the merge and now it conflicts.

**Comment by ullgren** [comment]
Thanks will push a fix rebased for the new master later today

**Comment by ullgren** [comment]
Fixed the conflicts and also fixed a bug in the output version v2 when return type was Void.

**Pull request merged**
